### ISSUE TITLE
https://guide.aotu.io/ 网站https证书异常，Chrome报不安全

### ISSUE THREAD

**Issue by StevenLi-phoenix** [o2team/guide#21]
https://guide.aotu.io/ 网站https证书异常，Chrome报不安全
<img width="318" alt="截屏2021-10-26 下午7 18 01" src="https://user-images.githubusercontent.com/75846119/138867478-79d1ffce-04d3-4ca5-b215-8342a827ae67.png">

估计是证书配置错误，并未配置子域名

**Comment by StevenLi-phoenix** [comment]
no reply.
And did not fixed

**Comment by caltonzhou** [comment]
> no reply. And did not fixed

提供一个自己部署的备用站点
https://f2e-guide.vercel.app/

**Comment by caltonzhou** [comment]
> no reply. And did not fixed

Luckily it's OK now.
